#!/usr/bin/env python

from __future__ import print_function

import os
import json
import pickle
import sys
import traceback

import pandas as pd

from sklearn import tree
from sklearn.model_selection import GridSearchCV

prefix = '/opt/ml/'

input_path = prefix + 'input/data'
output_path = os.path.join(prefix, 'output')
model_path = os.path.join(prefix, 'model')

channel_name='training'
training_path = os.path.join(input_path, channel_name)


def train():
    print('Starting the training.')
        
    input_files = [ os.path.join(training_path, file) for file in os.listdir(training_path) ]
    if len(input_files) == 0:
        raise ValueError(('error').format(training_path, channel_name))
    raw_data = [ pd.read_csv(file, header=None) for file in input_files ]
    train_data = pd.concat(raw_data)

    train_y = train_data.ix[:,0]
    train_X = train_data.ix[:,1:]

    params = {'min_samples_split':[2,4], 'min_samples_leaf':[1,2,3]}

    clf = tree.DecisionTreeClassifier()
        
    grid = GridSearchCV(estimator=clf, param_grid=params, cv=5)
    grid = grid.fit(train_X, train_y)

    with open(os.path.join(model_path, 'decision-tree-model.pkl'), 'wb') as out:
        pickle.dump(grid, out)
        print('Training complete.')

if __name__ == '__main__':
    train()

    sys.exit(0)
